export const schedules = [
  {
    id: 1,
    status: false,
    time: "03:00",
    task: "Tahajud",
  },
  {
    id: 2,
    status: false,
    time: "-",
    task: "Sholat fajr + Sholat Taubat",
  },
  {
    id: 3,
    status: false,
    time: "-",
    task: "Qobliyah + Sholat Shubuh + Dzikir",
  },
  {
    id: 4,
    status: false,
    time: "ba'da shubuh",
    task: "Baca qur'an minimal 5 menit",
  },
  {
    id: 5,
    status: false,
    time: "06:00",
    task: "Dengar kajian via youtube",
  },
  {
    id: 7,
    status: false,
    time: "-",
    task: "Olahraga 5 menit / push up 30x ",
  },
  {
    id: 8,
    status: false,
    time: "-",
    task: "Kuliah / Kerja",
  },
  {
    id: 9,
    status: false,
    time: "-",
    task: "Qobliyah + Shalat dhuhur + dzikir + Ba'diyah",
  },
  {
    id: 10,
    status: false,
    time: "-",
    task: "Shalat ashar + dzikir",
  },
  {
    id: 11,
    status: false,
    time: "-",
    task: "Shalat Maghrib + dzikir",
  },
  {
    id: 12,
    status: false,
    time: "-",
    task: "instighfar 100x",
  },
  {
    id: 13,
    status: false,
    time: "-",
    task: "Baca Qur'an minimal 5 menit",
  },
  {
    id: 14,
    status: false,
    time: "-",
    task: "Qobliyah + Isya' + Ba'diyah + witir",
  },
  {
    id: 15,
    status: false,
    time: "-",
    task: "shalawat 100x",
  },
  {
    id: 16,
    status: false,
    time: "-",
    task: "improve hard skill  / Liat tutorial + Praktek",
  },
  {
    id: 17,
    status: false,
    time: "-",
    task: "Baca buku minimal 3 lembar",
  },
  {
    id: 18,
    status: false,
    time: "-",
    task: "Dengerin Podcast edukasi Spotify sebelum tidur",
  },
];
